# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(431, 344)
        self.resetBtn = QtWidgets.QPushButton(Form)
        self.resetBtn.setGeometry(QtCore.QRect(20, 280, 111, 28))
        self.resetBtn.setObjectName("resetBtn")
        self.yesBtn = QtWidgets.QPushButton(Form)
        self.yesBtn.setGeometry(QtCore.QRect(240, 280, 93, 28))
        self.yesBtn.setObjectName("yesBtn")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 30, 351, 221))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.timeLimitLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.timeLimitLabel.setFont(font)
        self.timeLimitLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeLimitLabel.setObjectName("timeLimitLabel")
        self.gridLayout.addWidget(self.timeLimitLabel, 1, 0, 1, 1)
        self.difficultyLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.difficultyLabel.setFont(font)
        self.difficultyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.difficultyLabel.setObjectName("difficultyLabel")
        self.gridLayout.addWidget(self.difficultyLabel, 0, 0, 1, 1)
        self.timeLimitSlider = QtWidgets.QSlider(self.widget)
        self.timeLimitSlider.setMinimum(5)
        self.timeLimitSlider.setMaximum(100)
        self.timeLimitSlider.setProperty("value", 30)
        self.timeLimitSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeLimitSlider.setObjectName("timeLimitSlider")
        self.gridLayout.addWidget(self.timeLimitSlider, 1, 1, 1, 1)
        self.mistakeBatchSizeLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mistakeBatchSizeLabel.setFont(font)
        self.mistakeBatchSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mistakeBatchSizeLabel.setObjectName("mistakeBatchSizeLabel")
        self.gridLayout.addWidget(self.mistakeBatchSizeLabel, 2, 0, 1, 1)
        self.mistakeBatchSizeSlider = QtWidgets.QSlider(self.widget)
        self.mistakeBatchSizeSlider.setMinimum(1)
        self.mistakeBatchSizeSlider.setMaximum(20)
        self.mistakeBatchSizeSlider.setProperty("value", 5)
        self.mistakeBatchSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mistakeBatchSizeSlider.setObjectName("mistakeBatchSizeSlider")
        self.gridLayout.addWidget(self.mistakeBatchSizeSlider, 2, 1, 1, 1)
        self.difficultySlider = QtWidgets.QSlider(self.widget)
        self.difficultySlider.setMinimum(1)
        self.difficultySlider.setMaximum(8)
        self.difficultySlider.setProperty("value", 3)
        self.difficultySlider.setOrientation(QtCore.Qt.Horizontal)
        self.difficultySlider.setObjectName("difficultySlider")
        self.gridLayout.addWidget(self.difficultySlider, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.resetBtn.setText(_translate("Form", "恢复默认设置"))
        self.yesBtn.setText(_translate("Form", "确定"))
        self.yesBtn.setShortcut(_translate("Form", "Ctrl+S"))
        self.timeLimitLabel.setText(_translate("Form", "时间：30"))
        self.difficultyLabel.setText(_translate("Form", "难度：3"))
        self.mistakeBatchSizeLabel.setText(_translate("Form", "错题数：5"))
